# Generated by Django 4.1.3 on 2022-11-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='color',
            field=models.CharField(choices=[('R', 'Red'), ('B', 'Black'), ('BL', 'Blue'), ('Y', 'Yellow'), ('GR', 'Green'), ('G', 'Gray')], default='B', max_length=2),
        ),
    ]
