# Generated by Django 4.1.3 on 2022-11-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phone_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_id',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/phones/img'),
        ),
    ]
