# Generated by Django 4.1.3 on 2022-12-01 08:51

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_phone_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_id',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['brand', 'name']),
        ),
    ]
