# Generated by Django 4.1.3 on 2022-12-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_model_id_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_id',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(),
        ),
    ]
