# Generated by Django 4.1.3 on 2022-12-01 09:15

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_alter_model_id_slug_alter_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_id',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
