# Generated by Django 4.1.3 on 2022-12-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_alter_model_id_slug_alter_phone_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_id',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='slug',
        ),
    ]
