# Generated by Django 4.1.3 on 2022-12-04 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0008_remove_model_id_slug_remove_phone_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('specs', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='static/phones/img')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(choices=[('R', 'Red'), ('B', 'Black'), ('BL', 'Blue'), ('Y', 'Yellow'), ('GR', 'Green'), ('G', 'Gray')], default='B', max_length=2)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.brand')),
            ],
        ),
        migrations.RemoveField(
            model_name='phone',
            name='model_id',
        ),
        migrations.DeleteModel(
            name='Model_id',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
