# Generated by Django 4.1.3 on 2022-12-06 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('phones', '0009_product_remove_phone_model_id_delete_model_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProfileProducts', to='phones.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProfileProduct', to='users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='profiles',
            field=models.ManyToManyField(related_name='products', through='phones.ProfileProduct', to='users.profile'),
        ),
    ]
