# Generated by Django 4.1.3 on 2022-12-08 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0012_phonereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonereview',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
