# Generated by Django 4.1.3 on 2022-12-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpeg', upload_to='static/avatars'),
        ),
    ]
